# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-01-22 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20230122_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
