"""add_title_height

Revision ID: 3d4633dba811
Revises: ff6b60aa53fe
Create Date: 2020-06-15 22:55:56.116387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4633dba811'
down_revision = 'ff6b60aa53fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    op.drop_column('roles', 'height')
    # ### end Alembic commands ###
