"""add_nickname

Revision ID: 71b11e8c17fa
Revises: 3d4633dba811
Create Date: 2020-06-15 22:59:26.570033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71b11e8c17fa'
down_revision = '3d4633dba811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('nick_name', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['nick_name'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint('nick_name', 'roles', type_='unique')
    op.create_index('name', 'roles', ['name'], unique=True)
    op.drop_column('roles', 'nick_name')
    # ### end Alembic commands ###
